"""Regions and the service taxonomy.

Categories, their descriptions and their bullet lists come from SmartAWARE's
Website Content Brief. Subcategories come from the service list in the
developer requirements document; they are internal by default and drive task
categorisation rather than public pages.

None of this is hardcoded behaviour — it is seed data. Everything here is
editable, addable, reorderable, publishable and archivable from the Admin
Portal without a deploy.
"""

REGIONS: list[dict] = [
    {
        "slug": "uk",
        "name": "United Kingdom",
        "display_name": "UK Tax & Accounting Services",
        "currency_code": "GBP",
        "sort_order": 1,
    },
    {
        "slug": "india",
        "name": "India",
        "display_name": "India Tax & Accounting Services",
        "currency_code": "INR",
        "sort_order": 2,
    },
    {
        "slug": "uae",
        "name": "United Arab Emirates",
        "display_name": "UAE Tax & Accounting Services",
        "currency_code": "AED",
        "sort_order": 3,
    },
    {
        "slug": "oman",
        "name": "Oman",
        "display_name": "Oman Tax & Accounting Services",
        "currency_code": "OMR",
        "sort_order": 4,
    },
]

# Which categories each market offers. The brief is explicit that not every
# category applies everywhere and that a country page must show a service only
# once SmartAWARE confirms it — so anything absent here stays hidden.
REGION_SERVICES: dict[str, list[str]] = {
    "uk": [
        "personal-tax",
        "limited-company-accounting",
        "bookkeeping",
        "vat-services",
        "payroll",
        "cis-services",
        "business-registration",
        "tax-planning-advisory",
        "hmrc-companies-house-compliance",
        "management-accounts",
        "specialist-accounting",
        "additional-services",
    ],
    "india": [
        "personal-tax",
        "limited-company-accounting",
        "bookkeeping",
        "vat-services",
        "payroll",
        "business-registration",
        "tax-planning-advisory",
        "hmrc-companies-house-compliance",
        "management-accounts",
        "specialist-accounting",
        "additional-services",
    ],
    "uae": [
        "personal-tax",
        "limited-company-accounting",
        "bookkeeping",
        "vat-services",
        "payroll",
        "business-registration",
        "tax-planning-advisory",
        "management-accounts",
        "specialist-accounting",
        "additional-services",
    ],
    "oman": [
        "personal-tax",
        "limited-company-accounting",
        "bookkeeping",
        "vat-services",
        "payroll",
        "business-registration",
        "tax-planning-advisory",
        "management-accounts",
        "specialist-accounting",
        "additional-services",
    ],
}

# Local naming, where a market calls the same service something else.
REGION_NAME_OVERRIDES: dict[tuple[str, str], str] = {
    ("india", "vat-services"): "VAT / GST Services",
}

SERVICE_CATEGORIES: list[dict] = [
    {
        "slug": "personal-tax",
        "name": "Personal Tax",
        "icon_key": "user",
        "short_description": (
            "Professional support for individuals with their personal tax responsibilities."
        ),
        "details": [
            "Self Assessment Tax Returns.",
            "Personal tax compliance.",
            "Employment income and other taxable income.",
            "Property and rental income tax support.",
            "Capital gains tax-related support.",
            "Tax planning for individuals.",
            "International personal tax requirements, where applicable.",
        ],
        "subcategories": [
            "Self Assessment Tax Returns",
            "Personal Income Tax Returns",
            "Sole Trader Tax Returns",
            "Partnership Tax Returns",
            "Director Self Assessment Tax Returns",
            "Landlord Tax Returns",
            "Property Income Tax Returns",
            "Capital Gains Tax Calculations",
            "Capital Gains Tax Reporting",
            "Tax Refund Claims",
            "Tax Code Review",
            "Personal Tax Planning",
            "Pension Tax Planning",
            "Dividend Tax Planning",
            "HMRC Self Assessment Enquiries",
            "Tax Return Amendments",
            "Late Tax Return Assistance",
            "Personal Tax Liability Calculations",
            "Non-Resident Tax Returns",
            "Foreign Income Tax Reporting",
        ],
    },
    {
        "slug": "limited-company-accounting",
        "name": "Limited Company Accounting",
        "icon_key": "building",
        "short_description": ("Accounting and financial compliance support for limited companies."),
        "details": [
            "Company accounts preparation.",
            "Corporation Tax-related compliance.",
            "Annual accounts support.",
            "Accounting records and financial reporting.",
            "Company financial review.",
            "Accounting software support.",
        ],
        "subcategories": [
            "Limited Company Accounts Preparation",
            "Statutory Annual Accounts",
            "Corporation Tax Returns",
            "Corporation Tax Computations",
            "Monthly Bookkeeping",
            "Quarterly Bookkeeping",
            "Year-End Accounts Finalisation",
            "Director's Loan Account Management",
            "Dividend Accounting",
            "Shareholder Accounting",
            "Fixed Asset Accounting",
            "Management Accounts",
            "Financial Statements Preparation",
            "Company Accounting Reviews",
            "Dormant Company Accounts",
            "Company Accounts Amendments",
            "Company Closure Accounts",
            "Company Reorganisation Accounting",
        ],
    },
    {
        "slug": "bookkeeping",
        "name": "Bookkeeping",
        "icon_key": "book",
        "short_description": (
            "Accurate and organised financial record-keeping services for "
            "individuals and businesses."
        ),
        "details": [
            "Sales and purchase ledger maintenance.",
            "Bank reconciliation.",
            "Expense recording.",
            "Accounting software bookkeeping.",
            "Financial transaction recording.",
            "Regular bookkeeping support.",
        ],
        "subcategories": [
            "Daily Bookkeeping",
            "Weekly Bookkeeping",
            "Monthly Bookkeeping",
            "Quarterly Bookkeeping",
            "Bank Reconciliation",
            "Credit Card Reconciliation",
            "Sales Ledger Management",
            "Purchase Ledger Management",
            "Accounts Payable",
            "Accounts Receivable",
            "Sales Invoice Processing",
            "Purchase Invoice Processing",
            "Expense Management",
            "Receipt Management",
            "Supplier Reconciliation",
            "Customer Reconciliation",
            "Bank Transaction Posting",
            "Cash Book Maintenance",
            "General Ledger Maintenance",
            "Historical Bookkeeping",
            "Bookkeeping Cleanup",
            "Year-End Bookkeeping",
            "Accounting Software Migration",
            "Accounting Software Setup",
            "Chart of Accounts Setup",
        ],
    },
    {
        "slug": "vat-services",
        "name": "VAT Services",
        "icon_key": "receipt",
        "short_description": "VAT support for businesses with VAT-related responsibilities.",
        "details": [
            "VAT registration support.",
            "VAT return preparation.",
            "VAT compliance.",
            "VAT record review.",
            "VAT-related advisory.",
            "Assistance with VAT queries.",
        ],
        "subcategories": [
            "VAT Registration",
            "VAT Deregistration",
            "VAT Return Preparation",
            "VAT Return Submission",
            "VAT Calculations",
            "VAT Reconciliation",
            "VAT Compliance Reviews",
            "VAT Registration Threshold Monitoring",
            "VAT Scheme Selection Support",
            "Flat Rate VAT Support",
            "Standard VAT Scheme Support",
            "VAT Cash Accounting Scheme Support",
            "VAT Domestic Reverse Charge",
            "VAT International Transactions",
            "VAT Import and Export Support",
            "VAT Error Corrections",
            "VAT Refund Claims",
            "VAT Penalty Assistance",
            "VAT HMRC Enquiries",
            "Making Tax Digital for VAT",
        ],
    },
    {
        "slug": "payroll",
        "name": "Payroll",
        "icon_key": "users",
        "short_description": ("Payroll processing and related compliance support for businesses."),
        "details": [
            "Payroll processing.",
            "Employee salary calculations.",
            "Payslip preparation.",
            "PAYE-related compliance.",
            "Payroll records.",
            "Payroll reporting support.",
        ],
        "subcategories": [
            "Monthly Payroll Processing",
            "Weekly Payroll Processing",
            "Fortnightly Payroll Processing",
            "Director Payroll",
            "Employee Payroll",
            "PAYE Calculations",
            "National Insurance Calculations",
            "Payslip Preparation",
            "HMRC RTI Submissions",
            "New Employee Payroll Setup",
            "Employee Leaver Processing",
            "Payroll Year-End Processing",
            "P60 Preparation",
            "P11D Preparation",
            "Benefits-in-Kind Calculations",
            "Workplace Pension Payroll Support",
            "Holiday Pay Calculations",
            "Payroll Reconciliation",
            "Payroll Reporting",
            "Payroll Compliance Reviews",
        ],
    },
    {
        "slug": "cis-services",
        "name": "CIS Services",
        "icon_key": "hard-hat",
        "short_description": (
            "Construction Industry Scheme support for contractors and subcontractors."
        ),
        "details": [
            "CIS registration support.",
            "CIS monthly returns.",
            "Contractor and subcontractor records.",
            "CIS deductions and verification.",
            "CIS-related compliance support.",
        ],
        "subcategories": [
            "CIS Registration",
            "CIS Contractor Registration",
            "CIS Subcontractor Registration",
            "Subcontractor Verification",
            "CIS Monthly Returns",
            "CIS Deduction Calculations",
            "CIS Payment Statements",
            "CIS Gross Payment Status Support",
            "CIS Reconciliation",
            "CIS Bookkeeping",
            "CIS Tax Return Support",
            "CIS HMRC Enquiries",
        ],
    },
    {
        "slug": "business-registration",
        "name": "Business Registration",
        "icon_key": "clipboard",
        "short_description": (
            "Support for individuals and businesses establishing a new business."
        ),
        "details": [
            "Limited company registration.",
            "Business registration guidance.",
            "Sole trader registration support.",
            "Partnership registration guidance.",
            "Business structure considerations.",
            "Initial accounting and compliance setup.",
        ],
        "subcategories": [
            "Sole Trader Registration",
            "Limited Company Formation Support",
            "Partnership Registration",
            "HMRC UTR Registration",
            "Corporation Tax Registration",
            "VAT Registration",
            "PAYE Registration",
            "CIS Registration",
            "Business Bank Account Support",
            "Accounting System Setup",
            "Initial Bookkeeping Setup",
            "Business Structure Advice",
            "New Business Tax Planning",
            "Business Compliance Calendar Setup",
        ],
    },
    {
        "slug": "tax-planning-advisory",
        "name": "Tax Planning & Advisory",
        "icon_key": "compass",
        "short_description": (
            "Professional tax planning and advisory support based on individual "
            "and business circumstances."
        ),
        "details": [
            "Personal tax planning.",
            "Business tax planning.",
            "Corporation Tax planning.",
            "Tax-efficient business structuring.",
            "International tax-related advisory.",
            "Tax compliance review.",
            "General tax advisory.",
        ],
        "subcategories": [
            "Personal Tax Planning",
            "Corporation Tax Planning",
            "Salary and Dividend Planning",
            "Director Remuneration Planning",
            "Business Expense Planning",
            "Capital Gains Tax Planning",
            "Property Tax Planning",
            "Pension Tax Planning",
            "Business Structure Tax Planning",
            "Tax-Efficient Business Planning",
            "Business Acquisition Tax Planning",
            "Business Disposal Tax Planning",
            "International Tax Planning",
            "Tax Liability Forecasting",
            "Tax Compliance Reviews",
        ],
    },
    {
        "slug": "hmrc-companies-house-compliance",
        "name": "HMRC & Companies House Compliance",
        "icon_key": "shield",
        "short_description": (
            "Support with statutory compliance requirements for businesses and individuals."
        ),
        "details": [
            "HMRC compliance support.",
            "Companies House filing support.",
            "Annual confirmation statements.",
            "Corporation Tax compliance.",
            "Self Assessment compliance.",
            "Statutory filing deadlines.",
            "Compliance record review.",
        ],
        "subcategories": [
            "HMRC Registration Support",
            "HMRC Authorisation Support",
            "HMRC Correspondence Handling",
            "HMRC Tax Enquiry Assistance",
            "Self Assessment Enquiries",
            "Corporation Tax Enquiries",
            "VAT Enquiries",
            "PAYE Enquiries",
            "Tax Return Corrections",
            "Tax Penalty Assistance",
            "Late Filing Assistance",
            "Tax Payment Arrangement Support",
            "Companies House Confirmation Statement",
            "Companies House Filing Support",
            "Registered Office Support",
            "Company Director Changes",
            "Shareholder Changes",
            "Company Name Changes",
            "Company Closure Support",
        ],
    },
    {
        "slug": "management-accounts",
        "name": "Management Accounts",
        "icon_key": "chart",
        "short_description": (
            "Financial reporting services to help business owners understand business performance."
        ),
        "details": [
            "Monthly management accounts.",
            "Quarterly management accounts.",
            "Profit and loss reports.",
            "Balance sheet reporting.",
            "Cash flow reporting.",
            "Financial performance analysis.",
            "Business performance review.",
        ],
        "subcategories": [
            "Monthly Management Accounts",
            "Quarterly Management Accounts",
            "Profit & Loss Statements",
            "Balance Sheet Preparation",
            "Cash Flow Statements",
            "Cash Flow Forecasting",
            "Business Budgeting",
            "Budget vs Actual Analysis",
            "Financial Performance Reporting",
            "Business Profitability Analysis",
            "Business Financial Forecasting",
            "Debtors and Creditors Reporting",
            "Working Capital Analysis",
            "Business Growth Planning",
            "Financial Decision Support",
            "Business Valuation Support",
            "Financial Due Diligence",
            "Business Performance Reviews",
        ],
    },
    {
        "slug": "specialist-accounting",
        "name": "Specialist Accounting",
        "icon_key": "puzzle",
        "short_description": (
            "Accounting support for specific business and financial requirements."
        ),
        "details": [
            "Specialist accounting support.",
            "Business restructuring-related accounting.",
            "International accounting requirements.",
            "Financial reporting.",
            "Accounting review.",
            "Bespoke accounting solutions.",
        ],
        "subcategories": [
            "Company Secretarial Accounting Support",
            "Intercompany Accounting",
            "Multi-Currency Accounting",
            "Foreign Currency Reconciliation",
            "Stock and Inventory Accounting",
            "Cost Accounting",
            "Project Accounting",
            "Revenue Recognition Support",
            "Deferred Income Accounting",
            "Accruals and Prepayments",
            "Bad Debt Accounting",
            "Fixed Asset Register Maintenance",
            "Depreciation Calculations",
            "Financial Data Migration",
            "Accounting System Integration",
            "Financial Reporting Automation",
            "Audit Preparation Support",
            "Year-End Accountant Handover Support",
        ],
    },
    {
        "slug": "additional-services",
        "name": "Additional Services",
        "icon_key": "plus",
        "short_description": "Additional professional services based on client requirements.",
        "details": [
            "Financial administration support.",
            "Accounting software assistance.",
            "Business financial guidance.",
            "Tax documentation support.",
            "Bespoke accounting services.",
            "Other services approved by SmartAWARE.",
        ],
        "subcategories": [
            "Tax Return Review",
            "Tax Health Check",
            "Financial Records Review",
            "Accounting Records Reconstruction",
            "Business Compliance Health Check",
            "New Client Onboarding",
            "Accounting Software Training",
            "Bookkeeping Training",
            "Tax Document Preparation",
            "Financial Records Digitisation",
            "Secure Document Management",
            "Tax Deadline Reminders",
            "Annual Tax Compliance Review",
            "Business Finance Consultation",
            "Accountant Changeover Support",
        ],
    },
]
