"""add user token_version

Revision ID: b9abb09a801a
Revises: 9d71eb71dafe
Create Date: 2026-09-13 11:32:13.106615
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b9abb09a801a"
down_revision: str | None = "9d71eb71dafe"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required: the column is NOT NULL and the table may
    # already hold rows, which would otherwise fail on deploy.
    op.add_column(
        "users",
        sa.Column("token_version", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token_version")
    # ### end Alembic commands ###
